### ISSUE TITLE
Design sweep

### ISSUE THREAD

**Issue by ivanmauricio** [InFact-coop/discover#115]
We need to go through the app with fine-toothed comb

**Comment by nogainbar** [comment]
- [ ]  loading icon animation - svg is alredy in the drive and is animated
- [ ]  can we change the 'selected’ outline to be like in the designs? the one on select avatar and also on the select days page(thinner with some padding) on all the components - same as in choose technique
- [ ] set new goal: button needs to always be on the bottom as in designs
- [ ] links need to be blue - and connect to static ’tips' pages
- [ ] app bg colour is not blue its green rgba(78, 205, 196) at 25%
- [ ] my goal page bg is #F7FFF7 (not in the variables..)
- [ ] list of goals bg is yellow rgba(255, 230, 109, 0.5) at 5%
- [ ] help bg is blue rgba(17, 138, 178, 0.5) at 5%
- [ ] summary page is salmon red rgba(255, 107, 107, 0.5) at 5%
- [ ] tips static pages: 'tap anywhere’ should always be on the bottom of page and all the page should be tappable
- [ ] tips static pages: thanx got it should always be on the bottom of page and take you back to tips carousel
- [ ] outline on buttons - off

**Comment by lucymk** [comment]
@nogainbar where is the discover logo? i can't find it in the drive
