### ISSUE TITLE
Incorrect bot response in worry/problem flow

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#182]
![screen shot 2018-12-19 at 14 53 37](https://user-images.githubusercontent.com/13594621/50227741-5a86a380-039e-11e9-9403-eb7870feed71.png)

This then gets repeated:
![screen shot 2018-12-19 at 14 53 49](https://user-images.githubusercontent.com/13594621/50227746-5c506700-039e-11e9-9102-191815368d95.png)

**Comment by ivanmauricio** [comment]
@lucymk @rbraidwood closing this as it is now fixed.
