### ISSUE TITLE
Changed wording for tip summaries

### ISSUE THREAD

**Issue by rbraidwood** [InFact-coop/discover#183]
Hi. Please find document with wording edits to the tip summaries on the DISCOVERbot.

Note also the change of title for 'relaxed breathing technique' to 'deep breathing'. Please change this on the carousel.

[DISCOVER APP TECHNIQUE SUMMARY PAGES_IS edits.docx](https://github.com/InFact-coop/discover/files/3043417/DISCOVER.APP.TECHNIQUE.SUMMARY.PAGES_IS.edits.docx)

**Comment by ivanmauricio** [comment]
closed via #215
