### ISSUE TITLE
Correct typos/content in bot

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#189]
See spreadsheet.

**Comment by ivanmauricio** [comment]
[discover-chatbot-typos.pdf](https://github.com/InFact-coop/discover/files/3134868/discover-chatbot-typos.pdf)

**Comment by lucymk** [comment]
@rbraidwood there's a bit in this document in the "I've lost motivation" section where it says:

> o When the user selects other options which can help with sleep, and selects the relaxed breathing 
> technique, I think we need some text before the options, can we add:
> o X 

Is there supposed to be something else here? 😃

**Comment by rbraidwood** [comment]
@lucymk Hi. I am on the bot now and I can't find where I meant with this one... woops! I'll keep looking.

**Comment by rbraidwood** [comment]
nope... *closes*
