### ISSUE TITLE
Daily quote

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#194]
InFact to investigate different options with current quotes/designs - present to Ruth for confirmation.

[Daily.tips_April19 (1).docx](https://github.com/InFact-coop/discover/files/3142503/Daily.tips_April19.1.docx)

**Comment by lucymk** [comment]
@rbraidwood here are some ideas, what do you think?

**option 1:** quote with no attribution - the majority would fit into the intended design this way. Something like this:

![Screenshot 2019-05-03 at 16 50 12](https://user-images.githubusercontent.com/13594621/57149408-922d3f80-6dc3-11e9-9531-0896dbc4b351.png)


**option 2:** If attribution is desired, the quote couldn't be longer than e.g this one: 

![Screenshot 2019-05-03 at 16 52 55](https://user-images.githubusercontent.com/13594621/57149576-ec2e0500-6dc3-11e9-910f-c5306a41bb23.png)


**option 3:** an overlay that comes up with the tip when the user opens the app, they then have to close it to continue:

![Screenshot 2019-05-03 at 16 56 17](https://user-images.githubusercontent.com/13594621/57149811-7e360d80-6dc4-11e9-9819-e6d416b04bb8.png)

**Comment by rbraidwood** [comment]
Hi @lucymk @ivanmauricio @maxgerber 
We like option 2 best! how many quotes are excluded for being long, from the list we sent? And what is the word or character limit and I can send you some more. Could we title it 'Quote of the day' in small text above the quote (same size to the name under the quote)?

**Comment by lucymk** [comment]
Updates after chatting with Ruth:
- make it so quote only appears when you first open the app
- quote shouldn't change within the same day

**Comment by ivanmauricio** [comment]
@maxgerber Updates after chatting with Ruth:
- make it so quote only appears when you first open the app
- quote shouldn't change within the same day
