### ISSUE TITLE
Add copyright notice somewhere

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#195]
Look at designs and see how it would work

**Comment by ivanmauricio** [comment]
@rbraidwood We've had a look around and don't see an obvious place to put this. An option we thought of was putting in the initial chat flow along with the privacy policy but this seems overly obtrusive for students who it's not intended for. 

Do you have any thoughts on this?

**Comment by rbraidwood** [comment]
hi @ivanmauricio . Thanks for exploring this. It's the tip summaries which are in theory the workshop content which is copyrighted. How about on the main page of the 'Summary of DISCOVER tips' (the page with the carousel of tips). under the options and above the icons at the bottom, could we have a line saying
" © South London and Maudsley NHS Trust"

Or is that too long?

"

**Comment by lucymk** [comment]
Here are a few options (we tried on the first tips page as well):

![Screenshot 2019-05-03 at 17 51 43](https://user-images.githubusercontent.com/13594621/57152749-3adf9d00-6dcc-11e9-88eb-4157385dfbdd.png)
![Screenshot 2019-05-03 at 17 49 46](https://user-images.githubusercontent.com/13594621/57152752-3ca96080-6dcc-11e9-8f3f-3fb9386a9cf1.png)
![Screenshot 2019-05-03 at 17 48 32](https://user-images.githubusercontent.com/13594621/57152764-3f0bba80-6dcc-11e9-9e42-15cf2e899bb3.png)

**Comment by rbraidwood** [comment]
Hi @ivanmauricio . After discussion with the team we would rather have a copyright statement in the privacy policy (to cover our backs!) but not on the pages of the app. Could you send me the existing text for the privacy policy so I can check it and add the copy right statement and send back?

Thank you!

**Comment by rbraidwood** [comment]
@ivanmauricio thank you. 

Some edits:
- Please edit the text in third paragraph to updated "in May 2019."
- Delete the title "work well may use this information to" plus the two paragraphs under it. They don't apply to us as we don't collect their email addresses on the bot. Also the title doesn't make sense!
- In the paragraph under the table titled Data Processors, please capitalise "Trust" in the final sentence
- In the paragraph entitled "How will we notify you of changes to this policy?" is some of the second paragraph missing? Could we cut the sentence short at "We will notify you when we make changes to this policy."
- Please put DISCOVER team in capitals in the address at the bottom.
- Please add a title at the end of the document BEFORE the final paragraph ("How to contact us with questions or concerns"); title this "Copyright statement". Please add a paragraph under the title saying:

" © South London and Maudsley NHS Foundation Trust
All rights reserved. No part of this app may be reproduced or transmitted in any form or by any means without the prior permission of the DISCOVER Team in accordance with the provisions of the Copyright, Designs and Patents Act 1988."
