### ISSUE TITLE
Goal time selection

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#203]
@rbraidwood we don't completely understand what you mean by this:

> "If you select an option for when you’re doing your goal i.e ‘in the afternoon’ but don’t select a time. Is it possible for that to come up and it not read “00:00” (which is the default time)?"

Would you be able to clarify?

**Comment by rbraidwood** [comment]
The default time for your goal is midnight (00:00). So this comes up if the users don't select a time.

If people don't select a specific time, would it be OK for one not to show up?
