### ISSUE TITLE
Worry game question

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#205]
> - Change the text after ‘could you remind me of the difference between a worry and a problem?’ to:   “A worry is usually something personal to you”,  “Worries are often “what if” thoughts that go round in our minds in a negative, uncontrollable manner”,  “Lots of worrying…”, “Problems, however, tend to be more practical real-life issues.” , “And problems can be solved!”
> - The options after this don’t make sense, I think it’s as it’s missing some text first which says “Do you want to play a worry vs problem game?” Please add this

@rbraidwood we changed the above pieces of text, but couldn't replicate the issue where the text asking if the user wants to play a game was missing - can you test and see if it's still a problem?

**Comment by rbraidwood** [comment]
hi @lucymk . This works well now, thank you!

**Comment by ivanmauricio** [comment]
Awesome, will close issue
