### ISSUE TITLE
Link to app store instead of website

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#206]
When the apps Smiling Mind and Forest are referenced, the user should be linked to the app store for their device to download the app if they want. This should happen in a new tab, and not disturb the chat flow.

**Comment by ivanmauricio** [comment]
@rbraidwood I am looking for the `flowy` which is mentioned in one of the flows but I can't seem to find it. I found this [site](https://www.flowygame.com/) but it doesn't seem to load. I am wondering whether it was a project that got discontinued, do you have any ideas about this?

**Comment by ivanmauricio** [comment]
Also on the `Deep breathing` there is a reference to a Breathe app, do you know which one that is?

**Comment by rbraidwood** [comment]
Hi @ivanmauricio . It's this app for young people designed by a team in SLaM - https://play.google.com/store/apps/details?id=com.playlab.flowyfree&hl=en_GB

I am not sure if it's also on Apple!

**Comment by rbraidwood** [comment]
> Also on the `Deep breathing` summary there is a reference to a Breathe app, do you know which one that is?

Please remove this! The app no longer exists. Thanks @ivanmauricio  :)

**Comment by rbraidwood** [comment]
Thanks.Could you edit the copy to
"If you find it hard to do this on your own, you could try follow a guided breathing technique. You can find these on apps such as Smiling Mind, or on YouTube."

Could you link Smiling Mind to open the app?

And YouTube to this search: https://www.youtube.com/results?search_query=relaxed+breathing+exercises
