### ISSUE TITLE
Students think they have exhausted chat bot

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#207]
The opening of the majority of the content is via 'I'm feeling stressed right now' - if the user doesn't select this box, the content is limited and they may think they have seen everything. Should the option be phrased differently?

**Comment by lucymk** [comment]
@rbraidwood what do you think about this?

**Comment by rbraidwood** [comment]
hi @lucymk .That's a really good point. I wonder what the alternatives are that we could test out...

I want some advice
I am stressed     ['right now' is a bit specific?]

Any other ideas? I will ask the team too.

**Comment by lucymk** [comment]
@rbraidwood  maybe something more generic like "I'm not feeling great" could work?

**Comment by lucymk** [comment]
@rbraidwood do you think you'd like to change it and see if it makes a difference, or shall we leave it as is?

**Comment by rbraidwood** [comment]
Hi @lucymk 
Can we change it to 
"Remind me about the stress techniques"
and then the bot to reply saying
"Sure!"
"Tell me how you're feeling and I'll try and help you"

and then the existing options...

**Comment by lucymk** [comment]
Done!
