### ISSUE TITLE
Freezes after music

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#210]
![Screenshot 2019-05-02 at 16 34 32](https://user-images.githubusercontent.com/13594621/57087568-3ba6ff00-6cf8-11e9-9370-55a2fb317708.png)
@rbraidwood we can't replicate - can you check and see if this is still a problem?

**Comment by rbraidwood** [comment]
@lucymk this works now for me! Thanks!

**Comment by ivanmauricio** [comment]
Closing issue as now fixed
