### ISSUE TITLE
Breathing exercise should be slower

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#211]
When the bot talks the user through the breathing exercise, the messages should come through more slowly.

**Comment by lucymk** [comment]
Could potentially just add more "dots" messages to slow it down.

**Comment by lucymk** [comment]
@rbraidwood we've split up the messages to slow it down - do you want to have a look and let us know what you think?

**Comment by rbraidwood** [comment]
@lucymk great, thanks! Just did it and feeling calm now :)
