### ISSUE TITLE
"I'm exhausted" flow

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#212]
Skips straight to sleep tips, without the intermediary stages. 

When these get added back in, the following edits should be made:

> - When the user selects “I’m exhausted”, please add an ‘on’ in the next sentence so it reads: “Being tired can have a big impact on our stress levels and on our motivation to do things”
> - Change next sentence to “And when we’re stressed out, getting a good night’s sleep is more difficult”

**Comment by rbraidwood** [comment]
Yep, thank you!
