### ISSUE TITLE
'Tap anywhere' visibility

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/discover#213]
On some of the pages where the text fills the whole page (e.g. page 1 of procrastination tips, page 1 of time management tips, page 2 & 3 of sleeping tips), then ‘tap anywhere to continue’ appears over the other text. Please change this so the ‘tap anywhere’ is clearly visible somewhere on the screen. Similarly on the 4th page of procrastination tips

**Comment by lucymk** [comment]
@rbraidwood this is sorted (for most standard phone sizes these days) apart from on the first page of Mindfulness tips. There's just too much to squeeze in on that first page! Do you think some of it could be moved to the next page, or we could create an extra page in the middle?

**Comment by rbraidwood** [comment]
@lucymk . we could remove the last sentence on the first page of mindfulness tips "the more you do it..." ?

Does it fit then?

**Comment by lucymk** [comment]
@rbraidwood that would definitely help - you mean this whole section? "The more you do it, the easier it gets, and the more you will notice the benefits! You could also try a mindfulness exercise on an app like Headspace, Smiling Mind or Breathe."

**Comment by rbraidwood** [comment]
@lucymk . Oh.. I didn't see the second sentence as I think the tap anywhere must have been blocking it!
Or I'm looking at an older version of the app... the second sentence you refer to "You could also try a mindfulness exercise on an app like Headspace or Breathe" is on the second screen on the bot that I'm looking at...

Feel free to just move text to the next page and I will check it once it's been changed!

Also, can you remove reference to Breathe app which no longer exists and change it to just Headspace or Smiling Mind? thanks

**Comment by lucymk** [comment]
@rbraidwood I've taken out the Breathe app and moved some text around so it's like this now:
<img width="291" alt="Screenshot 2019-05-09 at 15 48 37" src="https://user-images.githubusercontent.com/13594621/57463080-05c2c700-7272-11e9-821b-01701cbcd6e8.png">
<img width="293" alt="Screenshot 2019-05-09 at 15 48 45" src="https://user-images.githubusercontent.com/13594621/57463084-06f3f400-7272-11e9-9910-8d73ba915717.png">

What do you think?

**Comment by rbraidwood** [comment]
Looks good! Thank you :) Sorry to edit the text again, but can you please
change the following sentences:
- 'Research suggests we have over 70,000 thoughts a day!"
-  "Our thoughts can drift to what has happened in the past, or to what
might go wrong in the future."

in second paragraph,
- "That means being aware of your breath, and what is going on around you
in the present moment"
