### ISSUE TITLE
Investigate PWA options

### ISSUE THREAD

**Issue by ivanmauricio** [InFact-coop/discover#44]
- Workbox (https://developers.google.com/web/tools/workbox/)
- Neutrino (https://neutrinojs.org/packages/pwa/)

**Comment by abdhalees** [comment]
@ivanmauricio 
I've tested both. 
- Both are easy to setup.
- workbox seems to be more well documented and have more features which we dont' need now but may need them in the future. 
So I'll go with workbox. I'll push after you confirm going with this option.

**Comment by ivanmauricio** [comment]
@abdhalees You're a coding machine! 🤖 😄 

Yes let's go with workbox, thanks for looking into them both!
